spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/restaurant_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password:
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
server:
  port: 8080
app:
  admin:
    username: ADMIN
    password: PASSWORD
    firstName: Dimitar
    lastName: Todorov
    phoneNumber: 0897065558
  init:
    users: true
    tables: true